import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const COOKIES_PATH = './cookies.txt';

export default {
  botName: 'Hannan Mariyam Bot',
  ownerNumber: '916360814849',
  cookiesPath: path.isAbsolute(COOKIES_PATH) ? COOKIES_PATH : path.join(__dirname, COOKIES_PATH),

  deliveryCaptions: [
    '💌 Forever mine, Hannan Mariyam, my wife',
    '✨ My queen Hannan Mariyam, my beautiful wife',
    '🌙 Hannan Mariyam, the moon of my heart',
    '🫶 My precious wife, Hannan Mariyam',
    '💫 Hannan Mariyam, my forever love',
    '🥀 My heart belongs to Hannan Mariyam',
    '❤️ Hannan Mariyam, my life partner',
    '🌹 My lovely wife, Hannan Mariyam',
    '🕊️ Hannan Mariyam, my peace and happiness',
    '💍 My soulmate Hannan Mariyam, my wife',
    '🌟 Hannan Mariyam, my shining star',
    '💕 My sweetest Hannan Mariyam, my wife',
    '👑 Hannan Mariyam, queen of my heart',
    '🦋 My beautiful Hannan Mariyam forever',
    '🌸 Hannan Mariyam, my heart’s favorite person',
    '💖 My darling wife, Hannan Mariyam',
    '☁️ Hannan Mariyam, my dream come true',
    '🔥 My endless love, Hannan Mariyam',
    '🌺 Hannan Mariyam, my special one',
    '💞 My forever wife, Hannan Mariyam',
    '🧸 Hannan Mariyam, my cute love',
    '🌈 My happiness is Hannan Mariyam',
    '💗 Hannan Mariyam, my only love',
    '🪐 My universe, Hannan Mariyam',
    '🤍 Hannan Mariyam, my forever and always',
    'Hannan Mariyam, Afroz Khan ki taraf se special salam 😌',
    'Motu, ready hau kya? Afroz Khan ne bheja 😳',
    'Paapu, idhar dekho zara 😌',
    'Giddu, suno na ek minute 👀',
    'Bacchi, tume kya malum hota ni 😳',
    'Muiya, reply do jaldi 😤',
    'Loaper, phir se drama shuru kya? 😭',
    'Blali, hasna nakko abhi 😭',
    'Bile, dekh zara kya bheja 😌',
    'Paapi, tum bhi na full nautanki 😭',
    'Puppy, cute se dekho isko 🐶',
    'Baccha, gussa nakko hona 😌',
    'Goru, kidhar ho tume? 👀',
    'Haizu, ek baar suno toh sahi 😤',
    'Motii, ye tumhare waste hai 😌',
    'Kaalu, idhar aa zara 👀',
    'Hannan Mariyam, Afroz Khan bolra suno zara 😌',
    'Motu, aisa karte so tume? 😳',
    'Paapu, nikarna waise nakko 😭',
    'Giddu, kaiku itna attitude? 😤',
    'Bacchi ku kya malum hota 😳',
    'Muiya, tumhara smile kidhar gaya? 😌',
    'Loaper, message dekho pehle 😭',
    'Blali, chup chap dekh lo 😤',
    'Bile, Afroz Khan ne yaad kiya 😌',
    'Paapi, itna late reply kaiku? 👀',
    'Puppy, good baccha bano zara 😌',
    'Baccha, faltu tension nakko lo 😌',
    'Goru, tum theek hau na? 🤍',
    'Haizu, zara pyaar se bolo 😭',
    'Motii, tum pehle dekh lo 😌',
    'Kaalu, full cute mood mein hau aaj 😌',
    'Hannan Mariyam, meri taraf se ek chotu sa message 😌',
    'Hannan Mariyam ke liye Afroz Khan ka message 😳',
    'Motu, kaiku ignore karre so? 😤',
    'Paapu, main bolra suno na 😭',
    'Giddu, abhi bhi nakhre? 👀',
    'Bacchi, tumko sab baad mein malum hota 😳',
    'Muiya, haan bolo abhi 😌',
    'Loaper, seedha seedha bolo kya hua 😭',
    'Blali, itna hasna mana hai 😤',
    'Bile, bas ek baar dekh lo 😌',
    'Paapi, baigan tum bhi na 😭',
    'Puppy, abhi smile karo zara 😌',
    'Baccha, meri baat maan lo 😌',
    'Goru, Afroz Khan ne bheja hai 👀',
    'Haizu, late mat karo reply 😤',
    'Motii, dekho kya surprise hai 😳',
    'Kaalu, suno meri baat 😌',
    'Hannan Mariyam, dil se bheja Afroz Khan ne 🤍',
    'Motu, tumhare liye special delivery 😌',
    'Paapu, kaiku itna chup hau? 👀',
    'Giddu, thoda serious suno abhi 😤',
    'Bacchi, tume malum bhi hai kya? 😳',
    'Muiya, kya karri ho abhi? 👀',
    'Loaper, aisa nakko karte 😭',
    'Blali, zara seedha baitho aur dekho 😭',
    'Bile, ye miss nakko karna 😌',
    'Paapi, tumhari harkate alag level 😭',
    'Puppy, arey wah good mood mein ho kya? 😌',
    'Baccha, samajh jao meri baat 😌',
    'Goru, kidhar gayab ho gaye? 👀',
    'Haizu, idhar dekho ek second 😳',
    'Motii, tumko ye pasand aayega 😌',
    'Kaalu, kaiku itna sharma ri ho? 😳',
    'Hannan Mariyam, Afroz Khan bolta hai smile karo 😌',
    'Motu, full mast rehna samjhi? 😌',
    'Paapu, tension kaiku leti? 😤',
    'Giddu, sab acha hoga inshaAllah 🤍',
    'Bacchi, Allah khush rakhe tume 🤍',
    'Muiya, zyada sochna nakko 😌',
    'Loaper, abhi bas khush raho 😤',
    'Blali, mood off nakko karo 😌',
    'Bile, Afroz Khan yaad karra tha 😳',
    'Paapi, thoda tameez se reply do 😭',
    'Puppy, cute si harkate kam karo 😭',
    'Baccha, tumko samjhana mushkil hai 😭',
    'Goru, tum sunte hi nai 😤',
    'Haizu, abhi bolo kya karna hai 👀',
    'Motii, idhar aao ek baat hai 😌',
    'Kaalu, nakhre band karo zara 😭',
    'Hannan Mariyam, tumhare waste ye rakha 😌',
    'Motu, meri taraf se salam bolo 😌',
    'Paapu, itna bhi busy nai hote 😤',
    'Giddu, message dekho aur bolo 😌',
    'Bacchi, choti si baat hai bas 😳',
    'Muiya, khairiyat hai na? 🤍',
    'Loaper, tumse baat karna matlab full comedy 😭',
    'Blali, hanso lekin zyada nai 😭',
    'Bile, zara dhyan se dekho 👀',
    'Paapi, abhi reply do na 😤',
    'Puppy, Afroz Khan ne special bheja 😌',
    'Baccha, samajh jao baat ko 😭',
    'Goru, full pyari baat hai ye 😌',
    'Haizu, tume kya lagta bolo 👀',
    'Motii, aaj mood kaisa hai? 😌',
    'Kaalu, ekdum mast rehna 😌',
    'Hannan Mariyam, Afroz Khan ki taraf se dua aur smile 🤍',
    'Motu Paapu Bacchi, sab naam tumhare hi hain 😭',
    'Hannan Mariyam, ye Afroz Khan ki real wali caption hai 😳'
  ]
};
